name: Build AdminApp APK

on:
  push:
    branches: [main]
    paths: [admin-app/**]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - run: cd admin-app && npm install
      
      - run: cd admin-app && eas build --platform android --wait

      - uses: actions/upload-artifact@v3
        with:
          name: AdminApp
          path: "admin-app/*.apk"
          retention-days: 30
